apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: build3-bc
spec:
  runPolicy: Serial
  triggers:
  - generic:
      secretReference:
        name: demo-git-generic-webhook-secret
    type: Generic

  - github:
      secretReference:
        name: demo-git-github-webhook-secret
    type: GitHub


  source:
    type: Git
    git:
      uri: https://github.com/jonggyoukim/developer-forum-demo.git


  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile


  output:
    to:
      kind: DockerImage
      name: "shiftyou/build3-app:last"
    pushSecret:
      name: dockerhub


  postCommit:
      script: "ls"

